import { readFile, writeFile } from "node:fs/promises";

const image = await readFile(new URL("../src/assets/brand.png", import.meta.url));
const width = image.readUInt32BE(16);
const height = image.readUInt32BE(20);
const symbol = {
  viewBox: `0 0 ${width} ${height}`,
  width,
  height,
  href: `data:image/png;base64,${image.toString("base64")}`,
};
await writeFile(
  new URL("../src/lib/brand-symbol.ts", import.meta.url),
  "// Generated by scripts/sync-brand.mjs from the original PNG; do not redraw or edit.\n" +
    `export const BRAND_SYMBOL = ${JSON.stringify(symbol, null, 2)} as const;\n`,
);
console.log("sync-brand: original CM monogram with UI seal synchronized");
