// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// This file is generated by scripts/generate-manifest.mjs
// It provides deprecated dummy exports to guide consumers to the correct entry point.

const throwError = (name: string, entry: string): never => {
  throw new Error(`O componente "${name}" deve ser importado de "cosmemilton-ui/${entry}". Atualize seu import.`);
};

function createProxy(name: string, entry: string) {
  return new Proxy(function() {}, {
    get() { throwError(name, entry); },
    apply() { throwError(name, entry); },
    construct() { return throwError(name, entry); }
  });
}

/** @deprecated O componente "CM_RICH_TEXT_DEFAULT_TOOLBAR" foi movido para "cosmemilton-ui/client". */
export const CM_RICH_TEXT_DEFAULT_TOOLBAR: unknown = /*#__PURE__*/ createProxy("CM_RICH_TEXT_DEFAULT_TOOLBAR", "client");
/** @deprecated O componente "CmAccordion" foi movido para "cosmemilton-ui/client". */
export const CmAccordion: unknown = /*#__PURE__*/ createProxy("CmAccordion", "client");
/** @deprecated O componente "CmAlert" foi movido para "cosmemilton-ui/client". */
export const CmAlert: unknown = /*#__PURE__*/ createProxy("CmAlert", "client");
/** @deprecated O componente "CmAlertDialog" foi movido para "cosmemilton-ui/client". */
export const CmAlertDialog: unknown = /*#__PURE__*/ createProxy("CmAlertDialog", "client");
/** @deprecated O componente "CmAppShell" foi movido para "cosmemilton-ui/client". */
export const CmAppShell: unknown = /*#__PURE__*/ createProxy("CmAppShell", "client");
/** @deprecated O componente "CmAspectRatio" foi movido para "cosmemilton-ui/client". */
export const CmAspectRatio: unknown = /*#__PURE__*/ createProxy("CmAspectRatio", "client");
/** @deprecated O componente "CmAvatar" foi movido para "cosmemilton-ui/client". */
export const CmAvatar: unknown = /*#__PURE__*/ createProxy("CmAvatar", "client");
/** @deprecated O componente "CmBarChart" foi movido para "cosmemilton-ui/client". */
export const CmBarChart: unknown = /*#__PURE__*/ createProxy("CmBarChart", "client");
/** @deprecated O componente "CmBox" foi movido para "cosmemilton-ui/server". */
export const CmBox: unknown = /*#__PURE__*/ createProxy("CmBox", "server");
/** @deprecated O componente "CmButton" foi movido para "cosmemilton-ui/client". */
export const CmButton: unknown = /*#__PURE__*/ createProxy("CmButton", "client");
/** @deprecated O componente "CmCalendar" foi movido para "cosmemilton-ui/client". */
export const CmCalendar: unknown = /*#__PURE__*/ createProxy("CmCalendar", "client");
/** @deprecated O componente "CmCarousel" foi movido para "cosmemilton-ui/client". */
export const CmCarousel: unknown = /*#__PURE__*/ createProxy("CmCarousel", "client");
/** @deprecated O componente "CmChartFrame" foi movido para "cosmemilton-ui/server". */
export const CmChartFrame: unknown = /*#__PURE__*/ createProxy("CmChartFrame", "server");
/** @deprecated O componente "CmCheckbox" foi movido para "cosmemilton-ui/client". */
export const CmCheckbox: unknown = /*#__PURE__*/ createProxy("CmCheckbox", "client");
/** @deprecated O componente "CmCodeBlock" foi movido para "cosmemilton-ui/client". */
export const CmCodeBlock: unknown = /*#__PURE__*/ createProxy("CmCodeBlock", "client");
/** @deprecated O componente "CmCol" foi movido para "cosmemilton-ui/server". */
export const CmCol: unknown = /*#__PURE__*/ createProxy("CmCol", "server");
/** @deprecated O componente "CmCollapsible" foi movido para "cosmemilton-ui/client". */
export const CmCollapsible: unknown = /*#__PURE__*/ createProxy("CmCollapsible", "client");
/** @deprecated O componente "CmCombobox" foi movido para "cosmemilton-ui/client". */
export const CmCombobox: unknown = /*#__PURE__*/ createProxy("CmCombobox", "client");
/** @deprecated O componente "CmCommand" foi movido para "cosmemilton-ui/client". */
export const CmCommand: unknown = /*#__PURE__*/ createProxy("CmCommand", "client");
/** @deprecated O componente "CmConfirmDialog" foi movido para "cosmemilton-ui/client". */
export const CmConfirmDialog: unknown = /*#__PURE__*/ createProxy("CmConfirmDialog", "client");
/** @deprecated O componente "CmContainer" foi movido para "cosmemilton-ui/server". */
export const CmContainer: unknown = /*#__PURE__*/ createProxy("CmContainer", "server");
/** @deprecated O componente "CmContextMenu" foi movido para "cosmemilton-ui/client". */
export const CmContextMenu: unknown = /*#__PURE__*/ createProxy("CmContextMenu", "client");
/** @deprecated O componente "CmDataTable" foi movido para "cosmemilton-ui/client". */
export const CmDataTable: unknown = /*#__PURE__*/ createProxy("CmDataTable", "client");
/** @deprecated O componente "CmDataTableActions" foi movido para "cosmemilton-ui/client". */
export const CmDataTableActions: unknown = /*#__PURE__*/ createProxy("CmDataTableActions", "client");
/** @deprecated O componente "CmDialog" foi movido para "cosmemilton-ui/client". */
export const CmDialog: unknown = /*#__PURE__*/ createProxy("CmDialog", "client");
/** @deprecated O componente "CmDrawer" foi movido para "cosmemilton-ui/client". */
export const CmDrawer: unknown = /*#__PURE__*/ createProxy("CmDrawer", "client");
/** @deprecated O componente "CmDropdownMenu" foi movido para "cosmemilton-ui/client". */
export const CmDropdownMenu: unknown = /*#__PURE__*/ createProxy("CmDropdownMenu", "client");
/** @deprecated O componente "CmEmpty" foi movido para "cosmemilton-ui/client". */
export const CmEmpty: unknown = /*#__PURE__*/ createProxy("CmEmpty", "client");
/** @deprecated O componente "CmField" foi movido para "cosmemilton-ui/server". */
export const CmField: unknown = /*#__PURE__*/ createProxy("CmField", "server");
/** @deprecated O componente "CmFileUpload" foi movido para "cosmemilton-ui/client". */
export const CmFileUpload: unknown = /*#__PURE__*/ createProxy("CmFileUpload", "client");
/** @deprecated O componente "CmForm" foi movido para "cosmemilton-ui/server". */
export const CmForm: unknown = /*#__PURE__*/ createProxy("CmForm", "server");
/** @deprecated O componente "CmGallery" foi movido para "cosmemilton-ui/client". */
export const CmGallery: unknown = /*#__PURE__*/ createProxy("CmGallery", "client");
/** @deprecated O componente "CmHoverCard" foi movido para "cosmemilton-ui/client". */
export const CmHoverCard: unknown = /*#__PURE__*/ createProxy("CmHoverCard", "client");
/** @deprecated O componente "CmInput" foi movido para "cosmemilton-ui/client". */
export const CmInput: unknown = /*#__PURE__*/ createProxy("CmInput", "client");
/** @deprecated O componente "CmInputOTP" foi movido para "cosmemilton-ui/client". */
export const CmInputOTP: unknown = /*#__PURE__*/ createProxy("CmInputOTP", "client");
/** @deprecated O componente "CmLightbox" foi movido para "cosmemilton-ui/client". */
export const CmLightbox: unknown = /*#__PURE__*/ createProxy("CmLightbox", "client");
/** @deprecated O componente "CmLineChart" foi movido para "cosmemilton-ui/client". */
export const CmLineChart: unknown = /*#__PURE__*/ createProxy("CmLineChart", "client");
/** @deprecated O componente "CmMenubar" foi movido para "cosmemilton-ui/client". */
export const CmMenubar: unknown = /*#__PURE__*/ createProxy("CmMenubar", "client");
/** @deprecated O componente "CmMultiSelect" foi movido para "cosmemilton-ui/client". */
export const CmMultiSelect: unknown = /*#__PURE__*/ createProxy("CmMultiSelect", "client");
/** @deprecated O componente "CmNavigationMenu" foi movido para "cosmemilton-ui/client". */
export const CmNavigationMenu: unknown = /*#__PURE__*/ createProxy("CmNavigationMenu", "client");
/** @deprecated O componente "CmPagination" foi movido para "cosmemilton-ui/client". */
export const CmPagination: unknown = /*#__PURE__*/ createProxy("CmPagination", "client");
/** @deprecated O componente "CmPopover" foi movido para "cosmemilton-ui/client". */
export const CmPopover: unknown = /*#__PURE__*/ createProxy("CmPopover", "client");
/** @deprecated O componente "CmPortal" foi movido para "cosmemilton-ui/client". */
export const CmPortal: unknown = /*#__PURE__*/ createProxy("CmPortal", "client");
/** @deprecated O componente "CmPortalPanel" foi movido para "cosmemilton-ui/client". */
export const CmPortalPanel: unknown = /*#__PURE__*/ createProxy("CmPortalPanel", "client");
/** @deprecated O componente "CmProgress" foi movido para "cosmemilton-ui/client". */
export const CmProgress: unknown = /*#__PURE__*/ createProxy("CmProgress", "client");
/** @deprecated O componente "CmProgressModal" foi movido para "cosmemilton-ui/client". */
export const CmProgressModal: unknown = /*#__PURE__*/ createProxy("CmProgressModal", "client");
/** @deprecated O componente "CmRadioGroup" foi movido para "cosmemilton-ui/client". */
export const CmRadioGroup: unknown = /*#__PURE__*/ createProxy("CmRadioGroup", "client");
/** @deprecated O componente "CmResizable" foi movido para "cosmemilton-ui/client". */
export const CmResizable: unknown = /*#__PURE__*/ createProxy("CmResizable", "client");
/** @deprecated O componente "CmRichTextEditor" foi movido para "cosmemilton-ui/client". */
export const CmRichTextEditor: unknown = /*#__PURE__*/ createProxy("CmRichTextEditor", "client");
/** @deprecated O componente "CmRow" foi movido para "cosmemilton-ui/server". */
export const CmRow: unknown = /*#__PURE__*/ createProxy("CmRow", "server");
/** @deprecated O componente "CmScrollArea" foi movido para "cosmemilton-ui/client". */
export const CmScrollArea: unknown = /*#__PURE__*/ createProxy("CmScrollArea", "client");
/** @deprecated O componente "CmSelect" foi movido para "cosmemilton-ui/client". */
export const CmSelect: unknown = /*#__PURE__*/ createProxy("CmSelect", "client");
/** @deprecated O componente "CmSidebar" foi movido para "cosmemilton-ui/client". */
export const CmSidebar: unknown = /*#__PURE__*/ createProxy("CmSidebar", "client");
/** @deprecated O componente "CmSplitButton" foi movido para "cosmemilton-ui/client". */
export const CmSplitButton: unknown = /*#__PURE__*/ createProxy("CmSplitButton", "client");
/** @deprecated O componente "CmStack" foi movido para "cosmemilton-ui/server". */
export const CmStack: unknown = /*#__PURE__*/ createProxy("CmStack", "server");
/** @deprecated O componente "CmSwitch" foi movido para "cosmemilton-ui/client". */
export const CmSwitch: unknown = /*#__PURE__*/ createProxy("CmSwitch", "client");
/** @deprecated O componente "CmTabs" foi movido para "cosmemilton-ui/client". */
export const CmTabs: unknown = /*#__PURE__*/ createProxy("CmTabs", "client");
/** @deprecated O componente "CmTabsContent" foi movido para "cosmemilton-ui/client". */
export const CmTabsContent: unknown = /*#__PURE__*/ createProxy("CmTabsContent", "client");
/** @deprecated O componente "CmTabsList" foi movido para "cosmemilton-ui/client". */
export const CmTabsList: unknown = /*#__PURE__*/ createProxy("CmTabsList", "client");
/** @deprecated O componente "CmTabsTrigger" foi movido para "cosmemilton-ui/client". */
export const CmTabsTrigger: unknown = /*#__PURE__*/ createProxy("CmTabsTrigger", "client");
/** @deprecated O componente "CmText" foi movido para "cosmemilton-ui/server". */
export const CmText: unknown = /*#__PURE__*/ createProxy("CmText", "server");
/** @deprecated O componente "CmTextarea" foi movido para "cosmemilton-ui/client". */
export const CmTextarea: unknown = /*#__PURE__*/ createProxy("CmTextarea", "client");
/** @deprecated O componente "CmThemeMenu" foi movido para "cosmemilton-ui/theme". */
export const CmThemeMenu: unknown = /*#__PURE__*/ createProxy("CmThemeMenu", "theme");
/** @deprecated O componente "CmThemeProvider" foi movido para "cosmemilton-ui/theme". */
export const CmThemeProvider: unknown = /*#__PURE__*/ createProxy("CmThemeProvider", "theme");
/** @deprecated O componente "CmThemeToggle" foi movido para "cosmemilton-ui/theme". */
export const CmThemeToggle: unknown = /*#__PURE__*/ createProxy("CmThemeToggle", "theme");
/** @deprecated O componente "CmToastNotice" foi movido para "cosmemilton-ui/client". */
export const CmToastNotice: unknown = /*#__PURE__*/ createProxy("CmToastNotice", "client");
/** @deprecated O componente "CmToastProvider" foi movido para "cosmemilton-ui/client". */
export const CmToastProvider: unknown = /*#__PURE__*/ createProxy("CmToastProvider", "client");
/** @deprecated O componente "CmTopbar" foi movido para "cosmemilton-ui/server". */
export const CmTopbar: unknown = /*#__PURE__*/ createProxy("CmTopbar", "server");
/** @deprecated O componente "CmTreeView" foi movido para "cosmemilton-ui/client". */
export const CmTreeView: unknown = /*#__PURE__*/ createProxy("CmTreeView", "client");
/** @deprecated O componente "CmUserMenu" foi movido para "cosmemilton-ui/client". */
export const CmUserMenu: unknown = /*#__PURE__*/ createProxy("CmUserMenu", "client");
/** @deprecated O componente "CmWizard" foi movido para "cosmemilton-ui/client". */
export const CmWizard: unknown = /*#__PURE__*/ createProxy("CmWizard", "client");
/** @deprecated O componente "cmChartColor" foi movido para "cosmemilton-ui/server". */
export const cmChartColor: unknown = /*#__PURE__*/ createProxy("cmChartColor", "server");
/** @deprecated O componente "formatFileSize" foi movido para "cosmemilton-ui/client". */
export const formatFileSize: unknown = /*#__PURE__*/ createProxy("formatFileSize", "client");
/** @deprecated O componente "useCmTheme" foi movido para "cosmemilton-ui/theme". */
export const useCmTheme: unknown = /*#__PURE__*/ createProxy("useCmTheme", "theme");
/** @deprecated O componente "useCmToast" foi movido para "cosmemilton-ui/client". */
export const useCmToast: unknown = /*#__PURE__*/ createProxy("useCmToast", "client");
/** @deprecated O componente "useOptionalCmTheme" foi movido para "cosmemilton-ui/theme". */
export const useOptionalCmTheme: unknown = /*#__PURE__*/ createProxy("useOptionalCmTheme", "theme");
/** @deprecated O componente "useTablePreference" foi movido para "cosmemilton-ui/client". */
export const useTablePreference: unknown = /*#__PURE__*/ createProxy("useTablePreference", "client");
/** @deprecated O componente "CmBadge" foi movido para "cosmemilton-ui/server". */
export const CmBadge: unknown = /*#__PURE__*/ createProxy("CmBadge", "server");
/** @deprecated O componente "CmBreadcrumb" foi movido para "cosmemilton-ui/server". */
export const CmBreadcrumb: unknown = /*#__PURE__*/ createProxy("CmBreadcrumb", "server");
/** @deprecated O componente "CmButtonGroup" foi movido para "cosmemilton-ui/server". */
export const CmButtonGroup: unknown = /*#__PURE__*/ createProxy("CmButtonGroup", "server");
/** @deprecated O componente "CmCard" foi movido para "cosmemilton-ui/server". */
export const CmCard: unknown = /*#__PURE__*/ createProxy("CmCard", "server");
/** @deprecated O componente "CmFilterBar" foi movido para "cosmemilton-ui/server". */
export const CmFilterBar: unknown = /*#__PURE__*/ createProxy("CmFilterBar", "server");
/** @deprecated O componente "CmGauge" foi movido para "cosmemilton-ui/server". */
export const CmGauge: unknown = /*#__PURE__*/ createProxy("CmGauge", "server");
/** @deprecated O componente "CmGrid" foi movido para "cosmemilton-ui/server". */
export const CmGrid: unknown = /*#__PURE__*/ createProxy("CmGrid", "server");
/** @deprecated O componente "CmGridContainer" foi movido para "cosmemilton-ui/server". */
export const CmGridContainer: unknown = /*#__PURE__*/ createProxy("CmGridContainer", "server");
/** @deprecated O componente "CmIcon" foi movido para "cosmemilton-ui/server". */
export const CmIcon: unknown = /*#__PURE__*/ createProxy("CmIcon", "server");
/** @deprecated O componente "CmIconBadge" foi movido para "cosmemilton-ui/server". */
export const CmIconBadge: unknown = /*#__PURE__*/ createProxy("CmIconBadge", "server");
/** @deprecated O componente "CmInputGroup" foi movido para "cosmemilton-ui/server". */
export const CmInputGroup: unknown = /*#__PURE__*/ createProxy("CmInputGroup", "server");
/** @deprecated O componente "CmItem" foi movido para "cosmemilton-ui/server". */
export const CmItem: unknown = /*#__PURE__*/ createProxy("CmItem", "server");
/** @deprecated O componente "CmKbd" foi movido para "cosmemilton-ui/server". */
export const CmKbd: unknown = /*#__PURE__*/ createProxy("CmKbd", "server");
/** @deprecated O componente "CmLabel" foi movido para "cosmemilton-ui/server". */
export const CmLabel: unknown = /*#__PURE__*/ createProxy("CmLabel", "server");
/** @deprecated O componente "CmLink" foi movido para "cosmemilton-ui/server". */
export const CmLink: unknown = /*#__PURE__*/ createProxy("CmLink", "server");
/** @deprecated O componente "CmMetricCard" foi movido para "cosmemilton-ui/server". */
export const CmMetricCard: unknown = /*#__PURE__*/ createProxy("CmMetricCard", "server");
/** @deprecated O componente "CmPage" foi movido para "cosmemilton-ui/server". */
export const CmPage: unknown = /*#__PURE__*/ createProxy("CmPage", "server");
/** @deprecated O componente "CmPageHeader" foi movido para "cosmemilton-ui/server". */
export const CmPageHeader: unknown = /*#__PURE__*/ createProxy("CmPageHeader", "server");
/** @deprecated O componente "CmSectionHeader" foi movido para "cosmemilton-ui/server". */
export const CmSectionHeader: unknown = /*#__PURE__*/ createProxy("CmSectionHeader", "server");
/** @deprecated O componente "CmSeparator" foi movido para "cosmemilton-ui/server". */
export const CmSeparator: unknown = /*#__PURE__*/ createProxy("CmSeparator", "server");
/** @deprecated O componente "CmStatusDot" foi movido para "cosmemilton-ui/server". */
export const CmStatusDot: unknown = /*#__PURE__*/ createProxy("CmStatusDot", "server");
/** @deprecated O componente "CmThemeScript" foi movido para "cosmemilton-ui/theme". */
export const CmThemeScript: unknown = /*#__PURE__*/ createProxy("CmThemeScript", "theme");
/** @deprecated O componente "CmTimeline" foi movido para "cosmemilton-ui/server". */
export const CmTimeline: unknown = /*#__PURE__*/ createProxy("CmTimeline", "server");
/** @deprecated O componente "CmToolbar" foi movido para "cosmemilton-ui/server". */
export const CmToolbar: unknown = /*#__PURE__*/ createProxy("CmToolbar", "server");
/** @deprecated O componente "auroraTheme" foi movido para "cosmemilton-ui/theme". */
export const auroraTheme: unknown = /*#__PURE__*/ createProxy("auroraTheme", "theme");
/** @deprecated O componente "blueTheme" foi movido para "cosmemilton-ui/theme". */
export const blueTheme: unknown = /*#__PURE__*/ createProxy("blueTheme", "theme");
/** @deprecated O componente "cmDensityClass" foi movido para "cosmemilton-ui/server". */
export const cmDensityClass: unknown = /*#__PURE__*/ createProxy("cmDensityClass", "server");
/** @deprecated O componente "cmFieldWidthStyle" foi movido para "cosmemilton-ui/server". */
export const cmFieldWidthStyle: unknown = /*#__PURE__*/ createProxy("cmFieldWidthStyle", "server");
/** @deprecated O componente "cmSizeValue" foi movido para "cosmemilton-ui/server". */
export const cmSizeValue: unknown = /*#__PURE__*/ createProxy("cmSizeValue", "server");
/** @deprecated O componente "cmSpacingValue" foi movido para "cosmemilton-ui/server". */
export const cmSpacingValue: unknown = /*#__PURE__*/ createProxy("cmSpacingValue", "server");
/** @deprecated O componente "cn" foi movido para "cosmemilton-ui/server". */
export const cn: unknown = /*#__PURE__*/ createProxy("cn", "server");
/** @deprecated O componente "customThemeCSS" foi movido para "cosmemilton-ui/theme". */
export const customThemeCSS: unknown = /*#__PURE__*/ createProxy("customThemeCSS", "theme");
/** @deprecated O componente "darkTheme" foi movido para "cosmemilton-ui/theme". */
export const darkTheme: unknown = /*#__PURE__*/ createProxy("darkTheme", "theme");
/** @deprecated O componente "defaultTheme" foi movido para "cosmemilton-ui/theme". */
export const defaultTheme: unknown = /*#__PURE__*/ createProxy("defaultTheme", "theme");
/** @deprecated O componente "extendThemes" foi movido para "cosmemilton-ui/theme". */
export const extendThemes: unknown = /*#__PURE__*/ createProxy("extendThemes", "theme");
/** @deprecated O componente "formatCNPJ" foi movido para "cosmemilton-ui/server". */
export const formatCNPJ: unknown = /*#__PURE__*/ createProxy("formatCNPJ", "server");
/** @deprecated O componente "formatCPF" foi movido para "cosmemilton-ui/server". */
export const formatCPF: unknown = /*#__PURE__*/ createProxy("formatCPF", "server");
/** @deprecated O componente "formatDate" foi movido para "cosmemilton-ui/server". */
export const formatDate: unknown = /*#__PURE__*/ createProxy("formatDate", "server");
/** @deprecated O componente "formatNCM" foi movido para "cosmemilton-ui/server". */
export const formatNCM: unknown = /*#__PURE__*/ createProxy("formatNCM", "server");
/** @deprecated O componente "formatPhone" foi movido para "cosmemilton-ui/server". */
export const formatPhone: unknown = /*#__PURE__*/ createProxy("formatPhone", "server");
/** @deprecated O componente "greenTheme" foi movido para "cosmemilton-ui/theme". */
export const greenTheme: unknown = /*#__PURE__*/ createProxy("greenTheme", "theme");
/** @deprecated O componente "midnightTheme" foi movido para "cosmemilton-ui/theme". */
export const midnightTheme: unknown = /*#__PURE__*/ createProxy("midnightTheme", "theme");
/** @deprecated O componente "orangeTheme" foi movido para "cosmemilton-ui/theme". */
export const orangeTheme: unknown = /*#__PURE__*/ createProxy("orangeTheme", "theme");
/** @deprecated O componente "redTheme" foi movido para "cosmemilton-ui/theme". */
export const redTheme: unknown = /*#__PURE__*/ createProxy("redTheme", "theme");
/** @deprecated O componente "resolveResponsiveNumber" foi movido para "cosmemilton-ui/server". */
export const resolveResponsiveNumber: unknown = /*#__PURE__*/ createProxy("resolveResponsiveNumber", "server");
/** @deprecated O componente "resolveResponsiveValue" foi movido para "cosmemilton-ui/server". */
export const resolveResponsiveValue: unknown = /*#__PURE__*/ createProxy("resolveResponsiveValue", "server");
/** @deprecated O componente "roseTheme" foi movido para "cosmemilton-ui/theme". */
export const roseTheme: unknown = /*#__PURE__*/ createProxy("roseTheme", "theme");
/** @deprecated O componente "schoolTheme" foi movido para "cosmemilton-ui/theme". */
export const schoolTheme: unknown = /*#__PURE__*/ createProxy("schoolTheme", "theme");
/** @deprecated O componente "themeSelector" foi movido para "cosmemilton-ui/theme". */
export const themeSelector: unknown = /*#__PURE__*/ createProxy("themeSelector", "theme");
/** @deprecated O componente "themeToCSSBlock" foi movido para "cosmemilton-ui/theme". */
export const themeToCSSBlock: unknown = /*#__PURE__*/ createProxy("themeToCSSBlock", "theme");
/** @deprecated O componente "themeToCSSVars" foi movido para "cosmemilton-ui/theme". */
export const themeToCSSVars: unknown = /*#__PURE__*/ createProxy("themeToCSSVars", "theme");
/** @deprecated O componente "themes" foi movido para "cosmemilton-ui/theme". */
export const themes: unknown = /*#__PURE__*/ createProxy("themes", "theme");
/** @deprecated O componente "violetTheme" foi movido para "cosmemilton-ui/theme". */
export const violetTheme: unknown = /*#__PURE__*/ createProxy("violetTheme", "theme");

/** @deprecated O entry root "cosmemilton-ui" foi removido. */
export default new Proxy(function() {}, { get() { throw new Error("cosmemilton-ui v3 não possui entry root. Importe de /client, /server ou /theme."); } });
